// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnoh98SESPZobbIwGdZ2uqGjJLuAjviQ',
    appId: '1:32662567958:web:dd7029eb67fd6ad9f10937',
    messagingSenderId: '32662567958',
    projectId: 'cardenaldevs',
    authDomain: 'cardenaldevs.firebaseapp.com',
    storageBucket: 'cardenaldevs.appspot.com',
    measurementId: 'G-10Q4SK0X1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYADyan5lGDSi6SSmkMmAKTGifMX7iHCQ',
    appId: '1:32662567958:android:fbaf7262994874d8f10937',
    messagingSenderId: '32662567958',
    projectId: 'cardenaldevs',
    storageBucket: 'cardenaldevs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxEz8LXRho8jpkJA9rkHpZPVKeXHu7ehQ',
    appId: '1:32662567958:ios:213641b99fb2efa7f10937',
    messagingSenderId: '32662567958',
    projectId: 'cardenaldevs',
    storageBucket: 'cardenaldevs.appspot.com',
    iosClientId: '32662567958-4j4poek7muncptmh263bv7s7qdnf83io.apps.googleusercontent.com',
    iosBundleId: 'com.cardenaldevs.cardenalDevs',
  );
}
